import http from 'node:http';

const DEFAULT_DEV_CORS_ORIGINS = new Set([
  'http://localhost:5173',
  'http://127.0.0.1:5173'
]);

function sendJson(response, statusCode, payload) {
  response.writeHead(statusCode, {
    'Content-Type': 'application/json; charset=utf-8'
  });
  response.end(JSON.stringify(payload, null, 2));
}

async function readBody(request) {
  const chunks = [];
  for await (const chunk of request) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf8');
}

async function parseRequestBody(request) {
  const rawBody = await readBody(request);
  const contentType = request.headers['content-type'] || '';

  if (contentType.includes('application/json')) {
    return rawBody ? JSON.parse(rawBody) : {};
  }

  const params = new URLSearchParams(rawBody);
  return Object.fromEntries(params.entries());
}

function normalizeOrigin(value) {
  const normalized = String(value || '').trim();
  if (!normalized) {
    return '';
  }

  try {
    const parsed = new URL(normalized);
    if (!parsed.protocol || !parsed.host) {
      return '';
    }
    return `${parsed.protocol}//${parsed.host}`;
  } catch {
    return '';
  }
}

function buildAllowedCorsOrigins(config) {
  const allowed = new Set(DEFAULT_DEV_CORS_ORIGINS);
  const baseOrigin = normalizeOrigin(config?.app?.baseUrl);
  if (baseOrigin) {
    allowed.add(baseOrigin);
  }

  const configuredOrigins = Array.isArray(config?.app?.corsOrigins) ? config.app.corsOrigins : [];
  for (const origin of configuredOrigins) {
    const normalized = normalizeOrigin(origin);
    if (normalized) {
      allowed.add(normalized);
    }
  }

  return allowed;
}

function applyCorsHeaders(request, response, allowedOrigins) {
  const origin = String(request.headers.origin || '').trim();
  if (!origin || !allowedOrigins.has(origin)) {
    return false;
  }

  response.setHeader('Access-Control-Allow-Origin', origin);
  response.setHeader('Vary', 'Origin');
  response.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  response.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  response.setHeader('Access-Control-Max-Age', '86400');
  return true;
}

export function createHttpServer({ taskService, llmService }) {
  const allowedCorsOrigins = buildAllowedCorsOrigins(taskService?.config || {});

  return http.createServer(async (request, response) => {
    const url = new URL(request.url, 'http://127.0.0.1');
    const pathname = url.pathname;

    try {
      const corsApplied = applyCorsHeaders(request, response, allowedCorsOrigins);
      if (request.method === 'OPTIONS') {
        if (corsApplied) {
          response.writeHead(204);
          response.end();
          return;
        }
        response.writeHead(404);
        response.end();
        return;
      }

      const hasUsableDraft = (detail) => Boolean(detail.latestDraft?.content || detail.latestDraft?.metadata?.reactionName);
      const shouldAutoGenerateDraft = (detail) => detail.domain?.capabilities?.drafting
        && detail.task.domain !== 'github_review'
        && detail.task.status !== 'failed'
        && (!detail.task.summary || !hasUsableDraft(detail));

      if (request.method === 'GET' && pathname === '/') {
        sendJson(response, 200, {
          ok: true,
          message: 'API 서버가 실행 중입니다. React UI는 별도 클라이언트 서버에서 제공합니다.',
          endpoints: {
            health: '/healthz',
            meta: '/api/meta',
            tasks: '/api/tasks'
          }
        });
        return;
      }

      if (request.method === 'GET' && pathname === '/healthz') {
        sendJson(response, 200, {
          ok: true,
          uptimeSeconds: Math.round(process.uptime())
        });
        return;
      }

      if (request.method === 'POST' && pathname === '/api/meetings/summarize') {
        const body = await parseRequestBody(request);
        const transcript = String(body.transcript || '').trim();
        if (!transcript) {
          sendJson(response, 400, {
            ok: false,
            error: '회의 전사 내용이 필요합니다'
          });
          return;
        }

        if (!llmService?.generateMeetingSummary) {
          throw new Error('회의 정리 서비스를 사용할 수 없습니다');
        }

        const result = await llmService.generateMeetingSummary({
          transcript,
          startedAt: String(body.startedAt || '').trim(),
          endedAt: String(body.endedAt || '').trim(),
          language: String(body.language || 'ko-KR').trim() || 'ko-KR'
        });

        sendJson(response, 200, {
          ok: true,
          summary: result.summary,
          polishedTranscript: result.polishedTranscript || '',
          document: result.document,
          provider: result.provider,
          agentProvider: result.agentProvider || ''
        });
        return;
      }

      if (request.method === 'GET' && pathname === '/api/tasks') {
        sendJson(response, 200, {
          tasks: taskService.listTasks({
            includeResolved: url.searchParams.get('includeResolved') === '1'
          }),
          projects: taskService.getCodeExecutionProjects(),
          readiness: taskService.getConnectorReadiness(),
          domains: taskService.getDomainCatalog()
        });
        return;
      }

      if (request.method === 'GET' && pathname === '/api/meta') {
        sendJson(response, 200, {
          projects: taskService.getCodeExecutionProjects(),
          readiness: taskService.getConnectorReadiness(),
          domains: taskService.getDomainCatalog(),
          projectsRoot: taskService.config.workspace.projectsRoot,
          defaultAgentProvider: taskService.config.agent?.defaultProvider || 'codex'
        });
        return;
      }

      if (request.method === 'POST' && pathname === '/api/tasks/code-execution') {
        const body = await parseRequestBody(request);
        const detail = await taskService.createCodeExecutionTask({
          command: body.command,
          projectId: body.projectId,
          baseBranch: body.baseBranch,
          branchName: body.branchName,
          agentProvider: body.agentProvider,
          needsPlanning: body.needsPlanning,
          needsDesign: body.needsDesign
        });
        sendJson(response, 201, detail);
        return;
      }

      const taskApiMatch = pathname.match(/^\/api\/tasks\/([^/]+)$/);
      if (request.method === 'GET' && taskApiMatch) {
        const taskId = decodeURIComponent(taskApiMatch[1]);
        let detail = taskService.getTaskDetail(taskId);
        if (shouldAutoGenerateDraft(detail)) {
          detail = await taskService.generateDraft(taskId, {});
        }
        if (detail.task.domain === 'slack_mention') {
          const analysisStatus = String(detail.task.payload?.codeReview?.analysisStatus || '').toLowerCase();
          if (!analysisStatus || analysisStatus === 'not_requested') {
            await taskService.startSlackCodeReview(taskId, {});
            detail = taskService.getTaskDetail(taskId);
          }
        }
        sendJson(response, 200, detail);
        return;
      }

      const runCodeTaskMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/run$/);
      if (request.method === 'POST' && runCodeTaskMatch) {
        const taskId = decodeURIComponent(runCodeTaskMatch[1]);
        const detail = await taskService.startCodeExecutionTask(taskId);
        sendJson(response, 200, {
          ok: true,
          taskId,
          status: detail.task.status
        });
        return;
      }

      const resumeCodeTaskMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/resume$/);
      if (request.method === 'POST' && resumeCodeTaskMatch) {
        const taskId = decodeURIComponent(resumeCodeTaskMatch[1]);
        const detail = await taskService.resumeCodeExecutionTask(taskId);
        sendJson(response, 200, {
          ok: true,
          taskId,
          status: detail.task.status
        });
        return;
      }

      const createPrMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/create-pr$/);
      if (request.method === 'POST' && createPrMatch) {
        const taskId = decodeURIComponent(createPrMatch[1]);
        const body = await parseRequestBody(request);
        const detail = await taskService.createCodeExecutionPullRequest(taskId, {
          branchName: body.branchName
        });
        sendJson(response, 200, {
          ok: true,
          taskId,
          status: detail.task.status
        });
        return;
      }

      if (request.method === 'POST' && pathname === '/internal/poll/slack-mentions') {
        const result = await taskService.pollSlackMentions();
        sendJson(response, 200, result);
        return;
      }

      if (request.method === 'POST' && pathname === '/internal/poll/github-reviews') {
        const result = await taskService.pollGitHubReviews();
        sendJson(response, 200, result);
        return;
      }

      const draftMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/draft$/);
      if (request.method === 'POST' && draftMatch) {
        const taskId = decodeURIComponent(draftMatch[1]);
        const body = await parseRequestBody(request);
        if (body.mode === 'generate') {
          const task = taskService.getTaskDetail(taskId).task;
          const includeCodeReviewContext = String(body.includeCodeReviewContext || '').toLowerCase() === 'true';
          const detail = await taskService.generateDraft(taskId, task.domain === 'slack_mention'
            ? {
              includeCodeReviewContext
            }
            : {
              generationAgentProvider: body.generationAgentProvider
            });
          const latestProvider = detail.latestDraft?.metadata?.provider || '';
          sendJson(response, 200, {
            ok: true,
            taskId,
            status: detail.task.status,
            provider: latestProvider
          });
          return;
        }

        taskService.saveDraft(taskId, {
          content: body.draft,
          summary: body.summary,
          metadata: {
            sendMode: body.sendMode,
            replyCategory: body.replyCategory,
            replyCategoryLabel: body.replyCategoryLabel,
            requestedAction: body.requestedAction,
            reactionName: body.reactionName
          }
        });
        sendJson(response, 200, {
          ok: true,
          taskId
        });
        return;
      }

      const codeReviewMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/code-review$/);
      if (request.method === 'POST' && codeReviewMatch) {
        const taskId = decodeURIComponent(codeReviewMatch[1]);
        const started = await taskService.startSlackCodeReview(taskId, {});
        sendJson(response, 200, {
          ok: true,
          taskId,
          started: started.started,
          alreadyRunning: started.alreadyRunning,
          status: started.detail.task.payload?.codeReview?.analysisStatus || ''
        });
        return;
      }

      const approveMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/approve$/);
      if (request.method === 'POST' && approveMatch) {
        const taskId = decodeURIComponent(approveMatch[1]);
        const detail = taskService.approveTask(taskId);
        sendJson(response, 200, {
          ok: true,
          taskId,
          status: detail.task.status,
          approvalState: detail.task.approval_state
        });
        return;
      }

      const ignoreMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/ignore$/);
      if (request.method === 'POST' && ignoreMatch) {
        const taskId = decodeURIComponent(ignoreMatch[1]);
        const detail = taskService.ignoreTask(taskId);
        sendJson(response, 200, {
          ok: true,
          taskId,
          status: detail.task.status
        });
        return;
      }

      const sendMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/send$/);
      if (request.method === 'POST' && sendMatch) {
        const taskId = decodeURIComponent(sendMatch[1]);
        const body = await parseRequestBody(request);
        taskService.saveDraft(taskId, {
          content: body.draft,
          summary: body.summary,
          metadata: {
            sendMode: body.sendMode,
            replyCategory: body.replyCategory,
            replyCategoryLabel: body.replyCategoryLabel,
            requestedAction: body.requestedAction,
            reactionName: body.reactionName
          }
        });
        const detail = await taskService.executeTask(taskId, {
          message: body.sendMode === 'reaction' ? '' : body.draft,
          reactionName: body.sendMode === 'reaction' ? body.reactionName : '',
          addReaction: body.sendMode === 'reaction'
        });
        sendJson(response, 200, {
          ok: true,
          taskId,
          status: detail.task.status
        });
        return;
      }

      sendJson(response, 404, {
        ok: false,
        error: '요청한 경로가 존재하지 않습니다.'
      });
    } catch (error) {
      sendJson(response, 500, {
        ok: false,
        error: error.message
      });
    }
  });
}
