import http from 'node:http';
import { parseRequestBody, readStringField, sendJson } from './http-utils.ts';
import { type LlmServiceApi, type TaskDetail, type TaskServiceApi } from './http-types.ts';

function getAnalysisStatus(detail: TaskDetail): string {
  return String(detail.task.payload?.codeReview?.analysisStatus || '');
}

export async function handleApplicationRoute({
  request,
  response,
  url,
  service,
  summarizer
}: {
  request: http.IncomingMessage;
  response: http.ServerResponse;
  url: URL;
  service: TaskServiceApi;
  summarizer: LlmServiceApi;
}): Promise<boolean> {
  const pathname = url.pathname;
  const hasUsableDraft = (detail: TaskDetail) => Boolean(
    detail.latestDraft?.content || detail.latestDraft?.metadata?.reactionName
  );
  const shouldAutoGenerateDraft = (detail: TaskDetail) => detail.domain?.capabilities?.drafting
    && detail.task.domain !== 'github_review'
    && detail.task.status !== 'failed'
    && (!detail.task.summary || !hasUsableDraft(detail));

  if (request.method === 'GET' && pathname === '/') {
    sendJson(response, 200, {
      ok: true,
      message: 'API 서버가 실행 중입니다. React UI는 별도 클라이언트 서버에서 제공합니다.',
      endpoints: {
        health: '/healthz',
        meta: '/api/meta',
        tasks: '/api/tasks'
      }
    });
    return true;
  }

  if (request.method === 'GET' && pathname === '/healthz') {
    sendJson(response, 200, {
      ok: true,
      uptimeSeconds: Math.round(process.uptime())
    });
    return true;
  }

  if (request.method === 'POST' && pathname === '/api/meetings/summarize') {
    const body = await parseRequestBody(request);
    const transcript = readStringField(body, 'transcript');
    if (!transcript) {
      sendJson(response, 400, {
        ok: false,
        error: '회의 전사 내용이 필요합니다'
      });
      return true;
    }

    if (!summarizer?.generateMeetingSummary) {
      throw new Error('회의 정리 서비스를 사용할 수 없습니다');
    }

    const result = await summarizer.generateMeetingSummary({
      transcript,
      startedAt: readStringField(body, 'startedAt'),
      endedAt: readStringField(body, 'endedAt'),
      language: readStringField(body, 'language') || 'ko-KR'
    });

    sendJson(response, 200, {
      ok: true,
      summary: result.summary,
      polishedTranscript: result.polishedTranscript || '',
      document: result.document,
      provider: result.provider,
      agentProvider: result.agentProvider || ''
    });
    return true;
  }

  if (request.method === 'GET' && pathname === '/api/tasks') {
    sendJson(response, 200, {
      tasks: service.listTasks({
        includeResolved: url.searchParams.get('includeResolved') === '1'
      }),
      projects: service.getCodeExecutionProjects(),
      readiness: service.getConnectorReadiness(),
      domains: service.getDomainCatalog()
    });
    return true;
  }

  if (request.method === 'GET' && pathname === '/api/meta') {
    sendJson(response, 200, {
      projects: service.getCodeExecutionProjects(),
      readiness: service.getConnectorReadiness(),
      domains: service.getDomainCatalog(),
      projectsRoot: service.config.workspace.projectsRoot,
      defaultAgentProvider: service.config.agent?.defaultProvider || 'codex'
    });
    return true;
  }

  if (request.method === 'POST' && pathname === '/api/tasks/code-execution') {
    const body = await parseRequestBody(request);
    const detail = await service.createCodeExecutionTask({
      command: readStringField(body, 'command'),
      projectId: readStringField(body, 'projectId'),
      baseBranch: readStringField(body, 'baseBranch'),
      branchName: readStringField(body, 'branchName'),
      agentProvider: readStringField(body, 'agentProvider'),
      needsPlanning: String(body.needsPlanning || '').toLowerCase() === 'true',
      needsDesign: String(body.needsDesign || '').toLowerCase() === 'true'
    });
    sendJson(response, 201, detail);
    return true;
  }

  const taskApiMatch = pathname.match(/^\/api\/tasks\/([^/]+)$/);
  if (request.method === 'GET' && taskApiMatch) {
    const taskId = decodeURIComponent(taskApiMatch[1]);
    let detail = service.getTaskDetail(taskId);
    if (shouldAutoGenerateDraft(detail)) {
      detail = await service.generateDraft(taskId, {});
    }
    if (detail.task.domain === 'slack_mention') {
      const analysisStatus = String(detail.task.payload?.codeReview?.analysisStatus || '').toLowerCase();
      if (!analysisStatus || analysisStatus === 'not_requested') {
        await service.startSlackCodeReview(taskId, {});
        detail = service.getTaskDetail(taskId);
      }
    }
    sendJson(response, 200, detail);
    return true;
  }

  const runCodeTaskMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/run$/);
  if (request.method === 'POST' && runCodeTaskMatch) {
    const taskId = decodeURIComponent(runCodeTaskMatch[1]);
    const detail = await service.startCodeExecutionTask(taskId);
    sendJson(response, 200, {
      ok: true,
      taskId,
      status: detail.task.status
    });
    return true;
  }

  const resumeCodeTaskMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/resume$/);
  if (request.method === 'POST' && resumeCodeTaskMatch) {
    const taskId = decodeURIComponent(resumeCodeTaskMatch[1]);
    const detail = await service.resumeCodeExecutionTask(taskId);
    sendJson(response, 200, {
      ok: true,
      taskId,
      status: detail.task.status
    });
    return true;
  }

  const createPrMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/create-pr$/);
  if (request.method === 'POST' && createPrMatch) {
    const taskId = decodeURIComponent(createPrMatch[1]);
    const body = await parseRequestBody(request);
    const detail = await service.createCodeExecutionPullRequest(taskId, {
      branchName: readStringField(body, 'branchName')
    });
    sendJson(response, 200, {
      ok: true,
      taskId,
      status: detail.task.status
    });
    return true;
  }

  if (request.method === 'POST' && pathname === '/internal/poll/slack-mentions') {
    const result = await service.pollSlackMentions();
    sendJson(response, 200, result);
    return true;
  }

  if (request.method === 'POST' && pathname === '/internal/poll/github-reviews') {
    const result = await service.pollGitHubReviews();
    sendJson(response, 200, result);
    return true;
  }

  const draftMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/draft$/);
  if (request.method === 'POST' && draftMatch) {
    const taskId = decodeURIComponent(draftMatch[1]);
    const body = await parseRequestBody(request);
    if (readStringField(body, 'mode') === 'generate') {
      const task = service.getTaskDetail(taskId).task;
      const includeCodeReviewContext = readStringField(body, 'includeCodeReviewContext').toLowerCase() === 'true';
      const detail = await service.generateDraft(taskId, task.domain === 'slack_mention'
        ? {
          includeCodeReviewContext
        }
        : {
          generationAgentProvider: readStringField(body, 'generationAgentProvider')
        });
      const latestProvider = detail.latestDraft?.metadata?.provider || '';
      sendJson(response, 200, {
        ok: true,
        taskId,
        status: detail.task.status,
        provider: latestProvider
      });
      return true;
    }

    service.saveDraft(taskId, {
      content: readStringField(body, 'draft'),
      summary: readStringField(body, 'summary'),
      metadata: {
        sendMode: readStringField(body, 'sendMode'),
        replyCategory: readStringField(body, 'replyCategory'),
        replyCategoryLabel: readStringField(body, 'replyCategoryLabel'),
        requestedAction: readStringField(body, 'requestedAction'),
        reactionName: readStringField(body, 'reactionName')
      }
    });
    sendJson(response, 200, {
      ok: true,
      taskId
    });
    return true;
  }

  const codeReviewMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/code-review$/);
  if (request.method === 'POST' && codeReviewMatch) {
    const taskId = decodeURIComponent(codeReviewMatch[1]);
    const started = await service.startSlackCodeReview(taskId, {});
    sendJson(response, 200, {
      ok: true,
      taskId,
      started: started.started,
      alreadyRunning: started.alreadyRunning,
      status: getAnalysisStatus(started.detail)
    });
    return true;
  }

  const approveMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/approve$/);
  if (request.method === 'POST' && approveMatch) {
    const taskId = decodeURIComponent(approveMatch[1]);
    const detail = service.approveTask(taskId);
    sendJson(response, 200, {
      ok: true,
      taskId,
      status: detail.task.status,
      approvalState: detail.task.approval_state
    });
    return true;
  }

  const ignoreMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/ignore$/);
  if (request.method === 'POST' && ignoreMatch) {
    const taskId = decodeURIComponent(ignoreMatch[1]);
    const detail = service.ignoreTask(taskId);
    sendJson(response, 200, {
      ok: true,
      taskId,
      status: detail.task.status
    });
    return true;
  }

  const sendMatch = pathname.match(/^\/api\/tasks\/([^/]+)\/send$/);
  if (request.method === 'POST' && sendMatch) {
    const taskId = decodeURIComponent(sendMatch[1]);
    const body = await parseRequestBody(request);
    const sendMode = readStringField(body, 'sendMode');
    const draft = readStringField(body, 'draft');
    const reactionName = readStringField(body, 'reactionName');
    service.saveDraft(taskId, {
      content: draft,
      summary: readStringField(body, 'summary'),
      metadata: {
        sendMode,
        replyCategory: readStringField(body, 'replyCategory'),
        replyCategoryLabel: readStringField(body, 'replyCategoryLabel'),
        requestedAction: readStringField(body, 'requestedAction'),
        reactionName
      }
    });
    const detail = await service.executeTask(taskId, {
      message: sendMode === 'reaction' ? '' : draft,
      reactionName: sendMode === 'reaction' ? reactionName : '',
      addReaction: sendMode === 'reaction'
    });
    sendJson(response, 200, {
      ok: true,
      taskId,
      status: detail.task.status
    });
    return true;
  }

  return false;
}
