import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { renderErrorPage, renderTaskDetailPage, renderTaskListPage } from './web/render.js';

function redirect(response, location) {
  response.writeHead(303, { Location: location });
  response.end();
}

function sendHtml(response, statusCode, html) {
  response.writeHead(statusCode, {
    'Content-Type': 'text/html; charset=utf-8'
  });
  response.end(html);
}

function sendJson(response, statusCode, payload) {
  response.writeHead(statusCode, {
    'Content-Type': 'application/json; charset=utf-8'
  });
  response.end(JSON.stringify(payload, null, 2));
}

async function readBody(request) {
  const chunks = [];
  for await (const chunk of request) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf8');
}

async function parseRequestBody(request) {
  const rawBody = await readBody(request);
  const contentType = request.headers['content-type'] || '';

  if (contentType.includes('application/json')) {
    return rawBody ? JSON.parse(rawBody) : {};
  }

  const params = new URLSearchParams(rawBody);
  return Object.fromEntries(params.entries());
}

function serveStatic(requestPath, response, cwd) {
  if (requestPath !== '/static/styles.css') {
    return false;
  }

  const cssPath = path.join(cwd, 'public', 'styles.css');
  response.writeHead(200, { 'Content-Type': 'text/css; charset=utf-8' });
  response.end(fs.readFileSync(cssPath, 'utf8'));
  return true;
}

function redirectToTaskOrList(response, nextTaskId, message) {
  if (nextTaskId) {
    redirect(response, `/tasks/${encodeURIComponent(nextTaskId)}?message=${encodeURIComponent(message)}`);
    return;
  }

  redirect(response, `/tasks?message=${encodeURIComponent(message)}`);
}

export function createHttpServer({ cwd, taskService }) {
  return http.createServer(async (request, response) => {
    const url = new URL(request.url, 'http://127.0.0.1');
    const pathname = url.pathname;
    const query = Object.fromEntries(url.searchParams.entries());

    try {
      const hasUsableDraft = (detail) => Boolean(detail.latestDraft?.content || detail.latestDraft?.metadata?.reactionName);
      const shouldAutoGenerateDraft = (detail) => detail.domain?.capabilities?.drafting
        && detail.task.domain !== 'github_review'
        && detail.task.status !== 'failed'
        && (!detail.task.summary || !hasUsableDraft(detail));

      if (serveStatic(pathname, response, cwd)) {
        return;
      }

      if (request.method === 'GET' && pathname === '/') {
        redirect(response, '/tasks');
        return;
      }

      if (request.method === 'GET' && pathname === '/healthz') {
        sendJson(response, 200, { ok: true, uptimeSeconds: Math.round(process.uptime()) });
        return;
      }

      if (request.method === 'GET' && pathname === '/tasks') {
        const html = renderTaskListPage({
          tasks: taskService.listTasks({
            includeResolved: url.searchParams.get('includeResolved') === '1'
          }),
          projects: taskService.getCodeExecutionProjects(),
          projectsRoot: taskService.config.workspace.projectsRoot,
          defaultAgentProvider: taskService.config.agent?.defaultProvider || 'codex',
          readiness: taskService.getConnectorReadiness(),
          domains: taskService.getDomainCatalog(),
          query
        });
        sendHtml(response, 200, html);
        return;
      }

      if (request.method === 'GET' && pathname === '/api/tasks') {
        sendJson(response, 200, {
          tasks: taskService.listTasks({
            includeResolved: url.searchParams.get('includeResolved') === '1'
          }),
          projects: taskService.getCodeExecutionProjects(),
          readiness: taskService.getConnectorReadiness()
        });
        return;
      }

      if ((request.method === 'POST' && pathname === '/tasks/code-execution/create') || (request.method === 'POST' && pathname === '/api/tasks/code-execution')) {
        const body = await parseRequestBody(request);
        const detail = await taskService.createCodeExecutionTask({
          command: body.command,
          projectId: body.projectId,
          baseBranch: body.baseBranch,
          agentProvider: body.agentProvider,
          needsPlanning: body.needsPlanning,
          needsDesign: body.needsDesign
        });
        const prefersJson = pathname.startsWith('/api/') || (request.headers.accept || '').includes('application/json');
        if (prefersJson) {
          sendJson(response, 201, detail);
          return;
        }
        redirect(response, `/tasks/${encodeURIComponent(detail.task.id)}?message=${encodeURIComponent('코드 작업을 생성하고 실행을 시작했습니다')}`);
        return;
      }

      const taskMatch = pathname.match(/^\/tasks\/([^/]+)$/);
      if (request.method === 'GET' && taskMatch) {
        const taskId = decodeURIComponent(taskMatch[1]);
        let detail = taskService.getTaskDetail(taskId);
        if (shouldAutoGenerateDraft(detail)) {
          detail = await taskService.generateDraft(taskId, {});
        }
        if (detail.task.domain === 'slack_mention') {
          const analysisStatus = String(detail.task.payload?.codeReview?.analysisStatus || '').toLowerCase();
          if (!analysisStatus || analysisStatus === 'not_requested') {
            await taskService.startSlackCodeReview(taskId, {});
            detail = taskService.getTaskDetail(taskId);
          }
        }
        sendHtml(response, 200, renderTaskDetailPage({
          detail,
          query,
          slackCodeReviewRepos: taskService.config.github?.repositories || []
        }));
        return;
      }

      const taskApiMatch = pathname.match(/^\/api\/tasks\/([^/]+)$/);
      if (request.method === 'GET' && taskApiMatch) {
        const taskId = decodeURIComponent(taskApiMatch[1]);
        let detail = taskService.getTaskDetail(taskId);
        if (shouldAutoGenerateDraft(detail)) {
          detail = await taskService.generateDraft(taskId, {});
        }
        if (detail.task.domain === 'slack_mention') {
          const analysisStatus = String(detail.task.payload?.codeReview?.analysisStatus || '').toLowerCase();
          if (!analysisStatus || analysisStatus === 'not_requested') {
            await taskService.startSlackCodeReview(taskId, {});
            detail = taskService.getTaskDetail(taskId);
          }
        }
        sendJson(response, 200, detail);
        return;
      }

      const runCodeTaskMatch = pathname.match(/^\/tasks\/([^/]+)\/run$/);
      if (request.method === 'POST' && runCodeTaskMatch) {
        const taskId = decodeURIComponent(runCodeTaskMatch[1]);
        await taskService.startCodeExecutionTask(taskId);
        redirect(response, `/tasks/${encodeURIComponent(taskId)}?message=${encodeURIComponent('코드 작업 실행을 시작했습니다')}`);
        return;
      }

      const createPrMatch = pathname.match(/^\/tasks\/([^/]+)\/create-pr$/);
      if (request.method === 'POST' && createPrMatch) {
        const taskId = decodeURIComponent(createPrMatch[1]);
        await taskService.createCodeExecutionPullRequest(taskId);
        redirect(response, `/tasks/${encodeURIComponent(taskId)}?message=${encodeURIComponent('PR을 생성했습니다')}`);
        return;
      }

      if (request.method === 'POST' && pathname === '/internal/poll/slack-mentions') {
        const result = await taskService.pollSlackMentions();
        const acceptsJson = (request.headers.accept || '').includes('application/json') || (request.headers['content-type'] || '').includes('application/json');
        if (acceptsJson) {
          sendJson(response, 200, result);
          return;
        }
        redirect(response, `/tasks?message=${encodeURIComponent(`Slack 멘션 영역을 업데이트했습니다: ${result.matchesFound}건 (코드검토 자동 시작 ${result.autoCodeReviewsStarted || 0}건)`)}`);
        return;
      }

      if (request.method === 'POST' && pathname === '/internal/poll/github-reviews') {
        const result = await taskService.pollGitHubReviews();
        const acceptsJson = (request.headers.accept || '').includes('application/json') || (request.headers['content-type'] || '').includes('application/json');
        if (acceptsJson) {
          sendJson(response, 200, result);
          return;
        }
        const skipped = result.alreadyReviewedSkipped + result.draftsSkipped + (result.selfAuthoredSkipped || 0);
        redirect(response, `/tasks?message=${encodeURIComponent(`GitHub PR 후보 수집이 끝났습니다: 후보 ${result.candidatesListed || 0}건, 스킵 ${skipped}건`)}`);
        return;
      }

      const draftMatch = pathname.match(/^\/tasks\/([^/]+)\/draft$/);
      if (request.method === 'POST' && draftMatch) {
        const taskId = decodeURIComponent(draftMatch[1]);
        const body = await parseRequestBody(request);
        if (body.mode === 'generate') {
          const task = taskService.getTaskDetail(taskId).task;
          const includeCodeReviewContext = String(body.includeCodeReviewContext || '').toLowerCase() === 'true';
          const detail = await taskService.generateDraft(taskId, task.domain === 'slack_mention'
            ? {
              includeCodeReviewContext
            }
            : {
              generationAgentProvider: body.generationAgentProvider
            });
          const redirectUrl = `/tasks/${encodeURIComponent(taskId)}?message=${encodeURIComponent('초안을 생성했습니다')}`;
          const acceptsJson = (request.headers.accept || '').includes('application/json');
          if (acceptsJson) {
            const latestProvider = detail.latestDraft?.metadata?.provider || '';
            sendJson(response, 200, {
              ok: true,
              taskId,
              status: detail.task.status,
              provider: latestProvider,
              redirectUrl
            });
            return;
          }
          redirect(response, redirectUrl);
          return;
        }

        taskService.saveDraft(taskId, {
          content: body.draft,
          summary: body.summary,
          metadata: {
            sendMode: body.sendMode,
            replyCategory: body.replyCategory,
            replyCategoryLabel: body.replyCategoryLabel,
            requestedAction: body.requestedAction,
            reactionName: body.reactionName
          }
        });
        redirect(response, `/tasks/${encodeURIComponent(taskId)}?message=${encodeURIComponent('초안을 저장했습니다')}`);
        return;
      }

      const codeReviewMatch = pathname.match(/^\/tasks\/([^/]+)\/code-review$/);
      if (request.method === 'POST' && codeReviewMatch) {
        const taskId = decodeURIComponent(codeReviewMatch[1]);
        const acceptsJson = (request.headers.accept || '').includes('application/json');
        const started = await taskService.startSlackCodeReview(taskId, {});
        if (acceptsJson) {
          sendJson(response, 200, {
            ok: true,
            taskId,
            started: started.started,
            alreadyRunning: started.alreadyRunning,
            status: started.detail.task.payload?.codeReview?.analysisStatus || ''
          });
          return;
        }
        const message = started.alreadyRunning
          ? '코드 검토가 이미 실행 중입니다'
          : '코드 검토를 시작했습니다. 코드검토 반영 초안은 별도 버튼으로 생성할 수 있습니다';
        redirect(response, `/tasks/${encodeURIComponent(taskId)}?message=${encodeURIComponent(message)}`);
        return;
      }

      const approveMatch = pathname.match(/^\/tasks\/([^/]+)\/approve$/);
      if (request.method === 'POST' && approveMatch) {
        const taskId = decodeURIComponent(approveMatch[1]);
        taskService.approveTask(taskId);
        redirect(response, `/tasks/${encodeURIComponent(taskId)}?message=${encodeURIComponent('작업을 승인했습니다')}`);
        return;
      }

      const ignoreMatch = pathname.match(/^\/tasks\/([^/]+)\/ignore$/);
      if (request.method === 'POST' && ignoreMatch) {
        const taskId = decodeURIComponent(ignoreMatch[1]);
        const task = taskService.getTaskDetail(taskId).task;
        const nextSlackTaskId = task.domain === 'slack_mention'
          ? taskService.getNextPendingTaskId(taskId, { domain: 'slack_mention' })
          : null;
        taskService.ignoreTask(taskId);
        if (task.domain === 'slack_mention') {
          redirectToTaskOrList(response, nextSlackTaskId, '작업을 무시했습니다');
          return;
        }
        redirect(response, `/tasks?message=${encodeURIComponent('작업을 무시했습니다')}`);
        return;
      }

      const sendMatch = pathname.match(/^\/tasks\/([^/]+)\/send$/);
      if (request.method === 'POST' && sendMatch) {
        const taskId = decodeURIComponent(sendMatch[1]);
        const body = await parseRequestBody(request);
        const task = taskService.getTaskDetail(taskId).task;
        const nextSlackTaskId = task.domain === 'slack_mention'
          ? taskService.getNextPendingTaskId(taskId, { domain: 'slack_mention' })
          : null;
        taskService.saveDraft(taskId, {
          content: body.draft,
          summary: body.summary,
          metadata: {
            sendMode: body.sendMode,
            replyCategory: body.replyCategory,
            replyCategoryLabel: body.replyCategoryLabel,
            requestedAction: body.requestedAction,
            reactionName: body.reactionName
          }
        });
        await taskService.executeTask(taskId, {
          message: body.sendMode === 'reaction' ? '' : body.draft,
          reactionName: body.sendMode === 'reaction' ? body.reactionName : '',
          addReaction: body.sendMode === 'reaction'
        });
        if (task.domain === 'slack_mention') {
          redirectToTaskOrList(response, nextSlackTaskId, '답변을 전송했습니다');
          return;
        }
        redirect(response, `/tasks?message=${encodeURIComponent(task.domain === 'github_review' ? '리뷰 코멘트를 게시했습니다' : '답변을 전송했습니다')}`);
        return;
      }

      sendHtml(response, 404, renderErrorPage({ title: '찾을 수 없음', message: '요청한 경로가 존재하지 않습니다.', query }));
    } catch (error) {
      const prefersJson = pathname.startsWith('/api/') || (request.headers.accept || '').includes('application/json');
      if (prefersJson) {
        sendJson(response, 500, {
          ok: false,
          error: error.message
        });
        return;
      }

      if (request.method === 'POST' && pathname.startsWith('/tasks/')) {
        const fallbackTarget = pathname.split('/').slice(0, 3).join('/');
        redirect(response, `${fallbackTarget}?error=${encodeURIComponent(error.message)}`);
        return;
      }

      sendHtml(response, 500, renderErrorPage({ title: '요청 실패', message: error.message, query }));
    }
  });
}
